"""Translation

Revision ID: 3570d6fc4510
Revises: 3e3fdfa4a426
Create Date: 2026-04-16 09:59:19.339764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3570d6fc4510'
down_revision: Union[str, Sequence[str], None] = '3e3fdfa4a426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('original_language', sa.String(length=10), nullable=True))
    op.add_column('document_chunks', sa.Column('translated_text_ro', sa.Text(), nullable=True))
    op.add_column('document_chunks', sa.Column('is_translated_to_ro', sa.Boolean(), nullable=True))
    op.add_column('document_chunks', sa.Column('translation_status', sa.String(length=30), nullable=True))
    op.add_column('document_chunks', sa.Column('translation_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'translation_model')
    op.drop_column('document_chunks', 'translation_status')
    op.drop_column('document_chunks', 'is_translated_to_ro')
    op.drop_column('document_chunks', 'translated_text_ro')
    op.drop_column('document_chunks', 'original_language')
    # ### end Alembic commands ###
