"""Initial

Revision ID: 3e3fdfa4a426
Revises: 
Create Date: 2026-04-16 09:58:42.698394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e3fdfa4a426'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_blocks_block_id'), table_name='document_blocks')
    op.drop_index(op.f('ix_document_blocks_doc_id'), table_name='document_blocks')
    op.drop_index(op.f('ix_document_blocks_page_number'), table_name='document_blocks')
    op.drop_table('document_blocks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('block_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doc_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kind', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bbox', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('normalized_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fingerprint_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('boilerplate_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('content_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_blocks_pkey'))
    )
    op.create_index(op.f('ix_document_blocks_page_number'), 'document_blocks', ['page_number'], unique=False)
    op.create_index(op.f('ix_document_blocks_doc_id'), 'document_blocks', ['doc_id'], unique=False)
    op.create_index(op.f('ix_document_blocks_block_id'), 'document_blocks', ['block_id'], unique=True)
    # ### end Alembic commands ###
